/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritances;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant food=new Restaurant("food","$$$$$");
        Review review=new Review("really good","ahmad",5);
        Review review1=new Review("really nice","ahmad alasaad",3);
        food.addReview(review);
        food.addReview(review1);
        System.out.println(food.toString());

    }
}
