/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritances;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void testInreview(){

        Review review=new Review("really good","ahmad",5);
        String accpectedResult="Review{" +
        "body='" + "really good" + '\'' +
        ", author='" + "ahmad" + '\'' +
        ", numberOfStars=" + 5 +
        '}';
        String actualResult=review.toString();
        assertEquals(actualResult,actualResult);
    }
    @Test void testInResturent(){
        Restaurant food=new Restaurant("food","$$$$$");
        String accpectedResult="Restaurant{" +
                "name='" + food + '\'' +
                ", numberOfStars=" + 0+
                ", priceCategory='" +"$$$$$"  + '\'' +
                ", reviews=" + "[]" +
                '}';
        String actualResult=food.toString();
        assertEquals(actualResult,actualResult);
    }
    @Test void testInAdd(){
        Restaurant food=new Restaurant("food","$$$$$");
        Review review=new Review("really good","ahmad",5);
        food.addReview(review);
        String accpectedResult="Restaurant{" +
                "name='" + food + '\'' +
                ", numberOfStars=" + 0+
                ", priceCategory='" +"$$$$$"  + '\'' +
                ", reviews=" + "[Review{body='really good', author='ahmad', numberOfStars=5.0}]" +
                '}';
        String actualResult=food.toString();
        assertEquals(actualResult,actualResult);
    }
}
