/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testInRollFunction(){
        Basiclibrary classUnderTest=new Basiclibrary();
        int[]actualResult=classUnderTest.roll(3);
        int length=actualResult.length;
        assertEquals(3,length);
    }

    @Test void testInContainsDuplicates(){
        Basiclibrary classUnderTest=new Basiclibrary();
        int[]arr={1,2,3,4};
        boolean actualResult=classUnderTest.containsDuplicates(arr);
        assertEquals(true,actualResult);
    }

    @Test void testInCalculatingAverages(){
        Basiclibrary classUnderTest=new Basiclibrary();
        int[]testArray={1,2,3,4,5};
        float actualResult=(float) classUnderTest.calculatingAverages(testArray);
        assertEquals(3.0,actualResult);
    }
    @Test void testInArrayOfArrays(){
        Basiclibrary classUnderTest=new Basiclibrary();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] actualResult= classUnderTest.arrayOfArrays(weeklyMonthTemperatures);
        int[]arr={55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(arr,actualResult);
    }
}
