/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.lang.*;

public class App {

    public static void main(String[] args) {

        Path path = Paths.get("app/src/main/resources/gates.js");
//        System.out.println(returnError(path));
        for (Object i:returnError(path)) {
            System.out.println(i);
        }
    }

    static ArrayList returnError(Path path){
        ArrayList<String> errorArray=new ArrayList<String>();
        try {
            List<String> fileLines = Files.readAllLines(path);
int i=0;

            for(String line : fileLines){

                if(!line.isEmpty()&&!(line.charAt(line.length()-1)=='{')&&!(line.charAt(line.length()-1)=='}')&&!(line.contains("if"))&&!(line.contains("else"))) {
                    if(line.charAt(line.length()-1)!=';'){
//                    System.out.println("Line"+ (i+1)+": Missing semicolon.");
                        errorArray.add("Line"+ (i+1)+": Missing semicolon.");
                }}
                i++;
            }

        } catch (IOException exception){
            System.out.println("An error occurred while reading from file");
        }
    return errorArray;
    }
}
